name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: get build time
      run: echo "TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/ericzty/www:${{ github.sha }}
          ghcr.io/ericzty/www:latest
        build-args: |
          COMMIT=${{ github.sha }}
          REF=${{ github.ref }}
          TIME=${{ env.TIME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: trigger www0 to update
      run: ${{ secrets.WTWWW0 }}
    - name: wait 10 sec
      run: sleep 10
    - name: see if www0 is updated
      run: 'curl -H "X-Server-Select: www0" https://ericz.dev | grep {{ github.sha }}'
    - name: trigger www1 to update
      run: ${{ secrets.WTWWW1 }}
    - name: wait 10 sec
      run: sleep 10
    - name: see if www1 is updated
      run: 'curl -H "X-Server-Select: www1" https://ericz.dev | grep {{ github.sha }}'
